version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - SECRET_KEY=replace-me
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_app_password
    restart: unless-stopped
